<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://apache.org"
         xmlns:xsi="http://w3.org"
         xsi:schemaLocation="http://apache.org https://apache.org">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>spring-boot-microservices-kafka-integration</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging> <!-- This MUST be pom -->

    <!-- These names must match your subfolder names exactly -->
    <modules>
        <module>microservice-producer</module>
        <module>microservice-notification-consumer</module>
    </modules>
</project>