spring:
    application:
        name: microservice-producer

    datasource:
        url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=UTC
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

        # Its Default Configuration this can be changed based on requirement
        hikari:
            pool-name: PersonHikariPool
            maximum-pool-size: 10
            minimum-idle: 10
            connection-timeout: 30000 # 30 Sec
            idle-timeout: 600000 # 10 min
            max-lifetime: 1800000 #30 min
            validation-timeout: 5000 #5 Sec
            leak-detection-threshold: 60000 #60 sec
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update

    kafka:
        bootstrap-servers: localhost:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.LongSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
    port: 8081

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics
    endpoint:
        health:
            show-details: always
info:
    app:
        name: Kafka Producer Service
        version: 1.0.0
        description: Kafka Producer Microservice

logging:
    level:
        "[org.springframework.security]": TRACE
        "[org.springframework.web]": TRACE

rate-limit:
    endpoints:
        - path: /person
          method: POST
          capacity: 10
          refill-minutes: 1

        - path: /person/all
          method: GET
          capacity: 1
          refill-minutes: 1
