spring:
    application:
        name: microservice-producer

    datasource:
        url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=UTC
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update

    kafka:
        bootstrap-servers: localhost:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.LongSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
    port: 8081

logging:
    level:
        org.springframework.security: TRACE
        org.springframework.web: TRACE
