spring:
    application:
        name: microservice-notification-consumer

    datasource:
        url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=UTC
        username: root
        password: root

    kafka:
        consumer:
            group-id: employee-group
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            enable-auto-commit: false
        properties:
            spring.json.trusted.packages: "com.kafka.microservice_producer.dto"
server:
    port: 8082
