spring:
    application:
        name: microservice-notification-consumer

    datasource:
        url: jdbc:mysql://localhost:3306/demo?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

        # Its Default Configuration this can be changed based on requirement
        hikari:
            pool-name: PersonHikariPool
            maximum-pool-size: 10
            minimum-idle: 10
            connection-timeout: 30000 # 30 Sec
            idle-timeout: 600000 # 10 min
            max-lifetime: 1800000 #30 min
            validation-timeout: 5000 #5 Sec
            leak-detection-threshold: 60000 #60 sec
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update

    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    kafka:
        consumer:
            group-id: person-group
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            enable-auto-commit: false
        properties:
            "[spring.json.trusted.packages]": "com.kafka.microservice_producer.dto"
server:
    port: 8082
